#!/usr/bin/env python3
"""
SIEM Forwarder for MariTime Security Monitor Alerts.

This module provides the SIEMForwarder class, which formats security alerts and
forwards them to a SIEM server (e.g. Splunk, QRadar, or generic Syslog collector)
using UDP or TCP syslog protocol. It supports CEF (Common Event Format), LEEF
(Log Event Extended Format), and standard RFC 3164 Syslog formatting.
"""

import logging
import socket
from datetime import datetime
from typing import Dict, Any

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s"
)
logger = logging.getLogger("siem_forwarder")


class SIEMForwarder:
    """Formats and forwards security alerts to a SIEM endpoint."""

    def __init__(
        self,
        host: str = "127.0.0.1",
        port: int = 514,
        protocol: str = "UDP",
        format_type: str = "CEF",
    ) -> None:
        """
        Initialize the SIEMForwarder.

        Args:
            host: The SIEM server hostname or IP address.
            port: The SIEM service port (default is 514).
            protocol: Communication protocol, "UDP" or "TCP" (case-insensitive).
            format_type: Serialization format, "CEF", "LEEF", or "SYSLOG" (case-insensitive).

        Raises:
            ValueError: If protocol or format_type is unsupported.
        """
        self.logger = logging.getLogger("siem_forwarder")
        self.host = host
        self.port = port
        self.protocol = protocol.upper()
        self.format_type = format_type.upper()

        if self.protocol not in ("UDP", "TCP"):
            raise ValueError(f"Invalid protocol '{protocol}'. Must be UDP or TCP.")
        if self.format_type not in ("CEF", "LEEF", "SYSLOG"):
            raise ValueError(f"Invalid format_type '{format_type}'. Must be CEF, LEEF, or SYSLOG.")

    def send_alert(self, alert: Dict[str, Any]) -> None:
        """
        Format the alert dictionary and send it to the configured SIEM host.

        If a socket error or host resolution failure occurs, the exception is
        caught and logged, allowing the application to degrade gracefully.

        Args:
            alert: The security alert dictionary generated by the rule engine.
        """
        try:
            formatted_msg = self._format_message(alert)
            self._send_payload(formatted_msg)
        except Exception as e:
            self.logger.error(f"Failed to forward alert to SIEM ({self.host}:{self.port}) via {self.protocol}: {e}")

    def _format_message(self, alert: Dict[str, Any]) -> str:
        """Format the alert dictionary according to format_type."""
        alert_type = alert.get("alert_type", "unknown_alert")
        message = alert.get("message", "No message provided")
        severity = alert.get("severity", "info")
        mitre_id = alert.get("mitre_id", "T0000")
        src = alert.get("packet_details", {}).get("source_ip", "unknown")

        if self.format_type == "CEF":
            # CEF:0|MariTime|SecurityMonitor|2.0|{alert_type}|{message}|{severity_num}|src={src} msg={msg} mitre={mitre_id}
            # Severity mapping: info=1, warning=3, high=7, critical=10
            sev_map = {"info": 1, "warning": 3, "high": 7, "critical": 10}
            sev_num = sev_map.get(severity.lower(), 1)
            # Standard CEF header fields escape pipe characters
            msg_escaped = message.replace("|", "\\|")
            return f"CEF:0|MariTime|SecurityMonitor|2.0|{alert_type}|{msg_escaped}|{sev_num}|src={src} msg={message} mitre={mitre_id}"

        elif self.format_type == "LEEF":
            # LEEF:1.0|MariTime|SecurityMonitor|2.0|{alert_type}|src={src}\tcat={alert_type}\tsev={severity}\tmsg={msg}
            return f"LEEF:1.0|MariTime|SecurityMonitor|2.0|{alert_type}|src={src}\tcat={alert_type}\tsev={severity}\tmsg={message}"

        elif self.format_type == "SYSLOG":
            # Standard RFC 3164 syslog header formatting: <14>{timestamp} MariTime {alert_type}: {message}
            now = datetime.now()
            month = now.strftime("%b")
            day = now.day
            day_str = f" {day}" if day < 10 else f"{day}"
            time_str = now.strftime("%H:%M:%S")
            timestamp = f"{month} {day_str} {time_str}"
            return f"<14>{timestamp} MariTime {alert_type}: {message}"

        return message

    def _send_payload(self, message: str) -> None:
        """Send raw message via UDP or TCP socket."""
        payload = (message + "\n").encode("utf-8")

        if self.protocol == "UDP":
            with socket.socket(socket.AF_INET, socket.SOCK_DGRAM) as s:
                s.settimeout(2.0)
                s.sendto(payload, (self.host, self.port))
        else:  # TCP
            with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
                s.settimeout(2.0)
                s.connect((self.host, self.port))
                s.sendall(payload)

        self.logger.debug(f"Alert successfully forwarded via {self.protocol}")
